---
title: "Untitled"
author: "Alberto"
date: "3/6/2019"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción


El análisis de riesgos, la estimación de la vida útil y el control dentro de la seguridad alimentaria requiere la aplicación de métodos relativamente avanzados de análisis estadístico. La implementación de estos métodos a situaciones reales puede ser compleja y, en mucho casos, requiere conocimientos de programación y desarrollo de software. Por esa razón, la Agencia Española de Seguridad Alimentaria y Nutrición (AESAN) ha implementado a través de la red BIOQURA un conjunto de herramientas de libre acceso para facilitar la aplicación de estos cálculos.

## Herramientas incluídas en esta aplicación

Las herramientas están divididas en dos grupos. En primer lugar, la red BIOQURA desarrolló las siguientes herramientas para apoyar estudios de vida útil:

- **T101: IC proporcion positivos** permite estimar la proporción de muestras positivas con respecto a un test (p.ej. presencia/ausencia de patógenos).
- **T102: Muestras con aw > limite** calcula la proporción de muestras con una actividad del agua superior a un límite en base a un muestreo.
- **T103: Muestras con pH > limite** calcula la proporción de muestras con un pH superior a un límite en base a un muestreo.

Posteriormente, 

## Sobre BIOQURA

La red BIOQURA se creo con el objetivo de desarrollar la estructura necesaria para llevar a cabo una priorización y evaluación de riesgo biológicos cuantitativa en España. Esta integrada por investigadores de distintos centros de investigación:

- Universidad Politécnica de Cartagena
- Universidad de León
- Universidad de Barcelona
- Universidad de Zaragoza
- Universidad de Córdoba
- Instituto de Agroquímica y Tecnología de Alimentos IATA - CSIC
- Centro de Edafología y Biología Aplicada del Segura CEBAS - CSIC
- Centro Nacional de Tecnología y Seguridad de Alimentos (CNTA)
- Tecnalia Research & Innovation
- Agencia Española de Seguridad Alimentaria y Nutrición (AESAN)

## Contacto

Para dudas con respecto al funcionamiento de la aplicación ponerse en contacto con Alberto Garre a través de:

alberto.garreperez(arroba)wur.nl

Para reportar bugs, por favor utilizar la página de GitHub del proyecto (link en la barra lateral).






